"""empty message

Revision ID: 683149b6760d
Revises: 77510f6aa738
Create Date: 2025-02-11 08:28:16.380843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '683149b6760d'
down_revision = '77510f6aa738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login')
    op.drop_table('signup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signup_pkey'),
    sa.UniqueConstraint('email', name='signup_email_key')
    )
    op.create_table('login',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='login_pkey'),
    sa.UniqueConstraint('email', name='login_email_key'),
    sa.UniqueConstraint('password', name='login_password_key')
    )
    # ### end Alembic commands ###
