"""empty message

Revision ID: 77510f6aa738
Revises: 5b83abd27753
Create Date: 2025-02-06 07:47:51.117117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77510f6aa738'
down_revision = '5b83abd27753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signup')
    # ### end Alembic commands ###
